# Generated by Django 5.0.2 on 2024-04-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otzivlar',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='otzivlar',
            name='img3',
        ),
    ]
