# Generated by Django 4.2.10 on 2024-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_otzivlar_img2_remove_otzivlar_img3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natijalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
